In [117]:
import pandas as pd

train = pd.read_csv('/home/qx816/notebooks/Ref_Notebooks/Practice/train.csv')

test = pd.read_csv('/home/qx816/notebooks/Ref_Notebooks/Practice/test.csv')

In [118]:
train.head(5)

,ID,para_0,para_1,para_2,para_3,para_4,para_5,para_6,para_7,para_8,...,para_42,para_43,para_44,para_45,para_46,para_47,para_48,para_49,para_50,Result
0,1,0.97122,0.83152,-0.57052,0.99590,0.762820,0.032973,-0.69248,-0.55397,-0.473470,...,-0.112290,0.12326,0.990180,-0.50457,0.12478,0.36049,-0.10158,-0.36256,0.21309,h0
1,2,-0.47565,0.43977,-0.50892,-0.35476,-0.435490,-0.618170,0.62963,-0.28157,-0.229950,...,0.026975,-0.55423,0.004867,-0.28715,-0.55678,-0.48990,-0.56377,-0.22229,0.63568,h0
2,3,-0.48641,-0.26590,-0.71295,-0.42638,-0.022972,-0.336080,0.15184,-0.28157,-0.227910,...,0.026975,-0.46864,-1.242700,-0.49820,-0.47720,-0.41047,0.22427,-0.21519,-0.16009,h3
3,4,-0.99236,-1.06970,-0.87621,-0.98453,-0.091183,-0.701840,0.35559,0.26323,0.138290,...,0.096610,-0.41310,-1.244000,-0.53871,-0.41947,-0.31858,0.63729,-0.21295,-0.57671,h0
4,5,-0.45878,-0.55809,-0.28180,-0.50519,-0.424630,0.050215,0.35867,0.67183,0.045001,...,0.305510,-0.57834,-1.519900,-0.46202,-0.55678,-0.48990,-0.27750,-0.46486,0.42153,h0

In [119]:
test.head(5)

,ID,para_0,para_1,para_2,para_3,para_4,para_5,para_6,para_7,para_8,...,para_41,para_42,para_43,para_44,para_45,para_46,para_47,para_48,para_49,para_50
0,B1,-0.715880,-3.00440,2.117800,-0.601430,2.215900,-0.537990,-1.763800,0.263230,-0.213340,...,0.00715,-0.11229,-0.53451,-2.27430,2.07240,-0.51227,-0.43436,1.008800,-0.46486,-0.873860
1,B2,-0.397340,-0.21463,-0.476530,-0.559270,0.070425,0.614320,-0.302890,-0.417770,-0.071453,...,0.51981,0.30551,-0.57834,-1.59760,-0.54541,-0.55678,-0.48990,0.052101,0.28711,-0.140210
2,B3,2.009400,0.83152,-0.570520,2.232600,1.965400,0.032973,-1.763800,-0.826370,-0.709950,...,-0.16374,-0.11229,2.41110,0.99018,-0.54541,2.47930,3.07240,2.257900,-0.46486,-2.131800
3,B4,-0.689930,-0.29367,-0.570520,-0.652960,-0.840610,-0.332450,0.878850,0.263230,0.425160,...,-0.16374,0.09661,-0.57834,-0.42393,-0.54541,-0.55678,-0.48990,0.229580,0.70488,-0.446610
4,B5,0.079707,0.28115,0.067832,0.063937,-0.065041,0.013117,0.052817,-0.009172,-0.029810,...,-0.16374,-0.11229,-0.44067,-0.43881,-0.51908,-0.45691,-0.36529,-0.304190,0.98631,0.004927

In [120]:
train.shape,test.shape

((1529, 53), (500, 52))

In [121]:
from sklearn.model_selection import train_test_split

y = train.Result
train.drop(["Result","ID"],axis=1,inplace=True)

In [122]:
train.head(2)

,para_0,para_1,para_2,para_3,para_4,para_5,para_6,para_7,para_8,para_9,...,para_41,para_42,para_43,para_44,para_45,para_46,para_47,para_48,para_49,para_50
0,0.97122,0.83152,-0.57052,0.99590,0.76282,0.032973,-0.69248,-0.55397,-0.47347,-0.09707,...,-0.16374,-0.112290,0.12326,0.990180,-0.50457,0.12478,0.36049,-0.10158,-0.36256,0.21309
1,-0.47565,0.43977,-0.50892,-0.35476,-0.43549,-0.618170,0.62963,-0.28157,-0.22995,2.35250,...,-0.16374,0.026975,-0.55423,0.004867,-0.28715,-0.55678,-0.48990,-0.56377,-0.22229,0.63568

In [123]:
# test_df = test.drop(["ID"],axis=1)

In [124]:

X_train, X_test, y_train, y_test = train_test_split(train, y , test_size=0.2,stratify=y)
print X_train.shape, y_train.shape
print X_test.shape, y_test.shape

(1223, 51) (1223,)
(306, 51) (306,)

In [125]:
X_train.columns

Index([u'para_0', u'para_1', u'para_2', u'para_3', u'para_4', u'para_5',
       u'para_6', u'para_7', u'para_8', u'para_9', u'para_10', u'para_11',
       u'para_12', u'para_13', u'para_14', u'para_15', u'para_16', u'para_17',
       u'para_18', u'para_19', u'para_20', u'para_21', u'para_22', u'para_23',
       u'para_24', u'para_25', u'para_26', u'para_27', u'para_28', u'para_29',
       u'para_30', u'para_31', u'para_32', u'para_33', u'para_34', u'para_35',
       u'para_36', u'para_37', u'para_38', u'para_39', u'para_40', u'para_41',
       u'para_42', u'para_43', u'para_44', u'para_45', u'para_46', u'para_47',
       u'para_48', u'para_49', u'para_50'],
      dtype='object')

In [126]:
test.shape

(500, 52)

In [127]:
test.columns

Index([u'ID', u'para_0', u'para_1', u'para_2', u'para_3', u'para_4', u'para_5',
       u'para_6', u'para_7', u'para_8', u'para_9', u'para_10', u'para_11',
       u'para_12', u'para_13', u'para_14', u'para_15', u'para_16', u'para_17',
       u'para_18', u'para_19', u'para_20', u'para_21', u'para_22', u'para_23',
       u'para_24', u'para_25', u'para_26', u'para_27', u'para_28', u'para_29',
       u'para_30', u'para_31', u'para_32', u'para_33', u'para_34', u'para_35',
       u'para_36', u'para_37', u'para_38', u'para_39', u'para_40', u'para_41',
       u'para_42', u'para_43', u'para_44', u'para_45', u'para_46', u'para_47',
       u'para_48', u'para_49', u'para_50'],
      dtype='object')

In [128]:
sk = test.columns.tolist()

In [129]:
features = []
ls=['ID']
for i in sk:
    if i not in ls:
        features.append(i)

In [130]:
features

['para_0',
 'para_1',
 'para_2',
 'para_3',
 'para_4',
 'para_5',
 'para_6',
 'para_7',
 'para_8',
 'para_9',
 'para_10',
 'para_11',
 'para_12',
 'para_13',
 'para_14',
 'para_15',
 'para_16',
 'para_17',
 'para_18',
 'para_19',
 'para_20',
 'para_21',
 'para_22',
 'para_23',
 'para_24',
 'para_25',
 'para_26',
 'para_27',
 'para_28',
 'para_29',
 'para_30',
 'para_31',
 'para_32',
 'para_33',
 'para_34',
 'para_35',
 'para_36',
 'para_37',
 'para_38',
 'para_39',
 'para_40',
 'para_41',
 'para_42',
 'para_43',
 'para_44',
 'para_45',
 'para_46',
 'para_47',
 'para_48',
 'para_49',
 'para_50']

In [131]:
from sklearn.neighbors import KNeighborsClassifier

In [132]:

model = KNeighborsClassifier(n_neighbors=3,metric="euclidean")

In [133]:

model.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [134]:
train_accuracy = model.score(X_train,y_train)
test_accuracy = model.score(X_test,y_test)
print(train_accuracy,test_accuracy)

(0.70973017170891251, 0.48039215686274511)

In [113]:
type(model.predict(test[features]))

numpy.ndarray

In [139]:
test["Result"] = model.predict(test[features]).astype(float)

ValueError: could not convert string to float: h3

In [115]:
 model.predict(test[features])

array(['h3', 'h1', 'h0', 'h1', 'h0', 'h0', 'h2', 'h4', 'h0', 'h0', 'h5',
       'h2', 'h1', 'h1', 'h0', 'h0', 'h4', 'h0', 'h1', 'h1', 'h0', 'h4',
       'h0', 'h3', 'h0', 'h4', 'h0', 'h1', 'h0', 'h0', 'h5', 'h2', 'h0',
       'h3', 'h0', 'h0', 'h0', 'h1', 'h0', 'h0', 'h1', 'h5', 'h5', 'h1',
       'h0', 'h1', 'h1', 'h2', 'h0', 'h0', 'h1', 'h1', 'h5', 'h3', 'h0',
       'h0', 'h5', 'h5', 'h1', 'h0', 'h0', 'h1', 'h0', 'h0', 'h0', 'h5',
       'h2', 'h0', 'h0', 'h0', 'h0', 'h0', 'h4', 'h0', 'h4', 'h4', 'h5',
       'h0', 'h1', 'h0', 'h1', 'h3', 'h1', 'h0', 'h3', 'h0', 'h1', 'h0',
       'h1', 'h0', 'h0', 'h0', 'h0', 'h5', 'h4', 'h0', 'h0', 'h0', 'h0',
       'h1', 'h1', 'h1', 'h0', 'h3', 'h0', 'h1', 'h0', 'h0', 'h0', 'h2',
       'h5', 'h0', 'h0', 'h2', 'h0', 'h1', 'h1', 'h0', 'h0', 'h0', 'h0',
       'h0', 'h3', 'h0', 'h3', 'h0', 'h2', 'h0', 'h1', 'h0', 'h2', 'h4',
       'h0', 'h0', 'h0', 'h1', 'h1', 'h2', 'h0', 'h1', 'h0', 'h1', 'h1',
       'h4', 'h0', 'h3', 'h2', 'h0', 'h5', 'h5', 'h3', 'h1', 'h0', 'h0',
       'h3', 'h0', 'h1', 'h3', 'h0', 'h0', 'h3', 'h1', 'h5', 'h0', 'h0',
       'h0', 'h0', 'h1', 'h2', 'h0', 'h1', 'h1', 'h3', 'h3', 'h0', 'h0',
       'h4', 'h0', 'h1', 'h4', 'h1', 'h0', 'h1', 'h0', 'h0', 'h1', 'h0',
       'h4', 'h4', 'h1', 'h0', 'h1', 'h1', 'h1', 'h0', 'h1', 'h3', 'h0',
       'h1', 'h1', 'h0', 'h4', 'h0', 'h5', 'h5', 'h0', 'h3', 'h0', 'h2',
       'h2', 'h1', 'h2', 'h0', 'h0', 'h4', 'h0', 'h0', 'h0', 'h0', 'h0',
       'h5', 'h0', 'h0', 'h0', 'h1', 'h5', 'h3', 'h1', 'h1', 'h1', 'h0',
       'h0', 'h3', 'h4', 'h0', 'h0', 'h0', 'h0', 'h3', 'h1', 'h4', 'h1',
       'h0', 'h3', 'h0', 'h1', 'h3', 'h1', 'h0', 'h0', 'h0', 'h0', 'h5',
       'h0', 'h1', 'h0', 'h0', 'h1', 'h0', 'h4', 'h1', 'h1', 'h0', 'h1',
       'h5', 'h0', 'h3', 'h0', 'h5', 'h0', 'h0', 'h0', 'h0', 'h0', 'h0',
       'h3', 'h0', 'h0', 'h4', 'h5', 'h4', 'h5', 'h0', 'h1', 'h1', 'h1',
       'h0', 'h0', 'h1', 'h0', 'h1', 'h0', 'h0', 'h1', 'h3', 'h0', 'h2',
       'h0', 'h0', 'h0', 'h1', 'h3', 'h5', 'h1', 'h0', 'h5', 'h0', 'h0',
       'h2', 'h4', 'h0', 'h1', 'h0', 'h1', 'h1', 'h3', 'h0', 'h2', 'h1',
       'h5', 'h1', 'h0', 'h1', 'h5', 'h1', 'h0', 'h0', 'h0', 'h0', 'h4',
       'h4', 'h2', 'h2', 'h0', 'h2', 'h0', 'h0', 'h5', 'h0', 'h0', 'h0',
       'h3', 'h3', 'h1', 'h4', 'h0', 'h0', 'h1', 'h0', 'h0', 'h2', 'h0',
       'h5', 'h0', 'h5', 'h1', 'h0', 'h0', 'h0', 'h0', 'h1', 'h5', 'h0',
       'h0', 'h0', 'h5', 'h1', 'h0', 'h0', 'h0', 'h2', 'h4', 'h0', 'h0',
       'h0', 'h0', 'h0', 'h2', 'h0', 'h1', 'h0', 'h3', 'h0', 'h1', 'h4',
       'h0', 'h1', 'h0', 'h0', 'h3', 'h0', 'h0', 'h3', 'h0', 'h4', 'h3',
       'h0', 'h5', 'h1', 'h0', 'h0', 'h1', 'h5', 'h2', 'h0', 'h1', 'h1',
       'h0', 'h1', 'h3', 'h3', 'h4', 'h1', 'h2', 'h1', 'h0', 'h1', 'h1',
       'h3', 'h1', 'h5', 'h0', 'h5', 'h0', 'h0', 'h0', 'h1', 'h3', 'h1',
       'h5', 'h1', 'h3', 'h0', 'h1', 'h4', 'h4', 'h1', 'h0', 'h0', 'h4',
       'h0', 'h1', 'h1', 'h5', 'h1', 'h0', 'h0', 'h2', 'h4', 'h3', 'h0',
       'h5', 'h5', 'h0', 'h1', 'h0', 'h3', 'h2', 'h1', 'h0', 'h0', 'h1',
       'h0', 'h1', 'h0', 'h0', 'h0', 'h0', 'h0', 'h0', 'h0', 'h0', 'h0',
       'h0', 'h3', 'h1', 'h0', 'h1', 'h0', 'h0', 'h0', 'h0', 'h3', 'h0',
       'h5', 'h0', 'h0', 'h0', 'h2', 'h1', 'h1', 'h0', 'h0', 'h1', 'h1',
       'h0', 'h1', 'h2', 'h0', 'h3'], dtype=object)

In [136]:
test.head()

,ID,para_0,para_1,para_2,para_3,para_4,para_5,para_6,para_7,para_8,...,para_42,para_43,para_44,para_45,para_46,para_47,para_48,para_49,para_50,Result
0,B1,-0.715880,-3.00440,2.117800,-0.601430,2.215900,-0.537990,-1.763800,0.263230,-0.213340,...,-0.11229,-0.53451,-2.27430,2.07240,-0.51227,-0.43436,1.008800,-0.46486,-0.873860,h3
1,B2,-0.397340,-0.21463,-0.476530,-0.559270,0.070425,0.614320,-0.302890,-0.417770,-0.071453,...,0.30551,-0.57834,-1.59760,-0.54541,-0.55678,-0.48990,0.052101,0.28711,-0.140210,h1
2,B3,2.009400,0.83152,-0.570520,2.232600,1.965400,0.032973,-1.763800,-0.826370,-0.709950,...,-0.11229,2.41110,0.99018,-0.54541,2.47930,3.07240,2.257900,-0.46486,-2.131800,h0
3,B4,-0.689930,-0.29367,-0.570520,-0.652960,-0.840610,-0.332450,0.878850,0.263230,0.425160,...,0.09661,-0.57834,-0.42393,-0.54541,-0.55678,-0.48990,0.229580,0.70488,-0.446610,h1
4,B5,0.079707,0.28115,0.067832,0.063937,-0.065041,0.013117,0.052817,-0.009172,-0.029810,...,-0.11229,-0.44067,-0.43881,-0.51908,-0.45691,-0.36529,-0.304190,0.98631,0.004927,h0

In [ ]:
num = input ("Enter max inputs :") 
print(num) 


# taking multiple inputs at a time  
for i in range(0:num):
	x = input("Enter multiple value: ")
	
print("Number of list is: ", x)